/**
 * Dynamic Component Registry
 * This file is managed by the Meta-Agent.
 * Components generated by the agent are registered here to be used in the dashboard.
 */

// Import dynamic components here
import { FinanceDashboard } from './FinanceDashboard';
import { EmailDashboard } from './EmailDashboard';

export const DynamicRegistry: Record<string, React.ComponentType<any>> = {
  // Add component mappings here
  'FinanceDashboard': FinanceDashboard,
  'EmailDashboard': EmailDashboard,
};

export type DynamicComponentType = keyof typeof DynamicRegistry;
